[tool.poetry]
name = "gopromax-converter"
version = "0.1.0"
description = ""
authors = ["Janne Tuukkanen <jatufin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt6 = "^6.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
